name: Release FrenOS ISO

on:
  push:
    tags: ['v*']

jobs:
  build:
    runs-on: ubuntu-latest
    container:
      image: archlinux:latest
      options: --privileged
    steps:
      - name: Install dependencies
        run: |
          pacman -Syu --noconfirm
          pacman -S --noconfirm archiso git

      - name: Checkout
        uses: actions/checkout@v4

      - name: Fix git permissions
        run: git config --global --add safe.directory "$GITHUB_WORKSPACE"

      - name: Build ISO
        run: |
          cd arf-linux-iso
          sed -i 's/sudo //g' build.sh
          ./build.sh

      - name: Create Release
        uses: softprops/action-gh-release@v2
        with:
          files: arf-linux-iso/out/*.iso
          generate_release_notes: true
